"""empty message

Revision ID: b46db44f6605
Revises: 
Create Date: 2018-01-15 22:23:23.941999

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b46db44f6605'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=32), nullable=True),
    sa.Column('last_name', sa.String(length=32), nullable=True),
    sa.Column('nickname', sa.String(length=32), nullable=True),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('mobile', sa.String(length=16), nullable=True),
    sa.Column('password_hash', sa.String(length=512), nullable=True),
    sa.Column('github_id', sa.String(length=32), nullable=True),
    sa.Column('github_login', sa.String(length=64), nullable=True),
    sa.Column('github_name', sa.String(length=32), nullable=True),
    sa.Column('github_email', sa.String(length=64), nullable=True),
    sa.Column('api_token', sa.String(length=512), nullable=True),
    sa.Column('login_count', sa.Integer(), nullable=True),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('activated', sa.Boolean(), nullable=True),
    sa.Column('disabled', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('github_id'),
    sa.UniqueConstraint('mobile')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
