"""empty message

Revision ID: f616154eacc0
Revises: b46db44f6605
Create Date: 2018-01-15 23:44:37.797222

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f616154eacc0'
down_revision = 'b46db44f6605'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('google_email', sa.String(length=64), nullable=True))
    op.add_column('user', sa.Column('google_id', sa.String(length=32), nullable=True))
    op.add_column('user', sa.Column('google_name', sa.String(length=32), nullable=True))
    op.create_unique_constraint(None, 'user', ['google_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'google_name')
    op.drop_column('user', 'google_id')
    op.drop_column('user', 'google_email')
    # ### end Alembic commands ###
